baseURL = 'https://piatrenka.com/'
defaultContentLanguage = 'en'
title = 'Ilya Piatrenka'
enableRobotsTXT = true

[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = 'series'

[sitemap]
  changefreq = 'daily'
  priority = 0.5

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
