colorScheme = 'gruvbox'
defaultAppearance = 'dark'
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ['posts']
# robots = ''

[header]
  layout = 'basic'

[footer]
  showCopyright = true
  showThemeAttribution = false

[homepage]
  layout = 'profile'
  homepageImage = ''
  showRecent = true
  showRecentItems = 5

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  showComments = false
  showPagination = true
  showViews = true

[umamiAnalytics]
  websiteid = "392f8993-ec17-49e4-b306-bcbbd45d3f02"
  domain = "umami.nidobit.com"
  enableTrackEvent = true

[firebase]
  apiKey = "AIzaSyDYe3FSEejf1WFeLATEW7jYcgvnIHOILBI"
  authDomain = "nidobit.firebaseapp.com"
  projectId = "nidobit"
  storageBucket = "nidobit.firebasestorage.app"
  messagingSenderId = "230054546283"
  appId = "1:230054546283:web:6488497aeeca77fd6a9a2e"
