colorScheme = 'gruvbox'
defaultAppearance = 'dark'
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ['posts']
# robots = ''

[header]
  layout = 'basic'

[footer]
  showCopyright = true
  showThemeAttribution = false

[homepage]
  layout = 'profile'
  homepageImage = ''
  showRecent = true
  showRecentItems = 5

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  showComments = false
  showPagination = true
  showViews = true

[umamiAnalytics]
  websiteid = "REPLACE_WITH_WEBSITE_ID"
  domain = "REPLACE_WITH_UMAMI_DOMAIN"
  enableTrackEvent = true

[firebase]
  apiKey = "REPLACE"
  authDomain = "REPLACE"
  projectId = "REPLACE"
  storageBucket = "REPLACE"
  messagingSenderId = "REPLACE"
  appId = "REPLACE"
  measurementId = "REPLACE"
